export const COURSES = [
  {
    slug: 'sslc-plus-two',
    title: 'SSLC / Plus Two',
    category: 'School Programs',
    description: 'Complete your secondary and higher secondary education through our flexible distance learning programs with expert guidance.',
    fullDescription: 'Our SSLC and Plus Two programs are designed for students who could not complete their secondary education due to personal or financial constraints. Through accredited distance learning, students can complete their schooling at their own pace and re-enter mainstream education or employment.',
    duration: '1-2 Years',
    mode: 'Distance',
    eligibility: 'Open to all ages',
    popular: false,
    icon: '📚',
    badge: 'Foundation',
    feeRange: '₹8,000 – ₹15,000 / year',
    careers: ['Government Jobs', 'Further Education', 'Vocational Training', 'Entry-level Employment'],
    highlights: ['Flexible schedule', 'Study from home', 'State board approved', 'Certificate valid nationwide'],
    universities: ['Kerala State Board', 'NIOS (National Institute of Open Schooling)'],
  },
  {
    slug: 'online-ug-degree',
    title: 'Online UG Degree',
    category: 'Under Graduate',
    description: 'Pursue your undergraduate degree online from UGC-approved universities. Programs in BA, BCom, BSc, BBA and more.',
    fullDescription: 'Our UG degree programs are offered through top UGC-DEB approved universities. You can choose from a wide range of disciplines including Arts, Commerce, Science, and Management. The degrees are fully recognised by the government and private sector employers across India.',
    duration: '3 Years',
    mode: 'Online',
    eligibility: 'Pass in Plus Two / equivalent',
    popular: true,
    icon: '🎓',
    badge: 'Popular',
    feeRange: '₹18,000 – ₹45,000 / year',
    careers: ['Banking & Finance', 'Corporate Sector', 'Government Services', 'Further PG Studies', 'Teaching'],
    highlights: ['UGC-DEB Approved', 'Live + recorded classes', 'Online exams', 'Valid for govt jobs', 'Semester-based'],
    universities: ['Aligarh Muslim University', 'Andhra University', 'GLA University', 'Jain University'],
  },
  {
    slug: 'online-pg-degree',
    title: 'Online PG Degree',
    category: 'Post Graduate',
    description: 'Advance your career with a postgraduate degree. MBA, MCA, MCom, MSc and more from top universities.',
    fullDescription: 'Our postgraduate programs are perfect for working professionals who want to upskill without leaving their jobs. Choose from MBA, MCA, MCom, MSc, MA, and more from NAAC accredited universities. Classes are fully online with flexible exam schedules.',
    duration: '2 Years',
    mode: 'Online',
    eligibility: 'Graduate in any discipline',
    popular: true,
    icon: '🏆',
    badge: 'Most Sought',
    feeRange: '₹25,000 – ₹75,000 / year',
    careers: ['Senior Management', 'IT & Tech Roles', 'Finance & Audit', 'Research & Academia', 'Entrepreneurship'],
    highlights: ['Industry-aligned curriculum', 'Placement support', 'Weekend batches', 'Case-study based learning', 'Alumni network'],
    universities: ['Manipal University', 'Amrita University', 'Jain University', 'Guru Kashi University'],
  },
  {
    slug: 'btech-mtech',
    title: 'B.Tech / M.Tech',
    category: 'Engineering',
    description: 'Get your engineering degree from recognised universities with industry-aligned curriculum and hands-on projects.',
    fullDescription: 'Engineering degrees through online and distance mode are now fully approved by AICTE and UGC. Our B.Tech and M.Tech programs cover Computer Science, Electronics, Mechanical, Civil, and more — with virtual labs and project-based assessments.',
    duration: '4 Years / 2 Years',
    mode: 'Online / Distance',
    eligibility: 'PCM in Plus Two / B.Tech for M.Tech',
    popular: false,
    icon: '⚙️',
    badge: 'Technical',
    feeRange: '₹40,000 – ₹90,000 / year',
    careers: ['Software Engineer', 'Systems Analyst', 'Project Manager', 'Research & Development', 'Core Engineering'],
    highlights: ['AICTE recognised', 'Virtual lab access', 'Industry mentors', 'Project-based assessment', 'Placement cell'],
    universities: ['Manipal University', 'Amrita University', 'Swami Vivekanand Subharti University'],
  },
  {
    slug: 'diploma-programs',
    title: 'Diploma Programs',
    category: 'Diploma',
    description: 'Short-term diploma courses designed for skill development and professional growth across multiple disciplines.',
    fullDescription: 'Diploma programs at TIMS are one-year courses that give you a recognised qualification in your chosen field. Available in Computer Applications, Business Management, Pharmacy, Education, and more. Ideal for students who want a faster route to employment.',
    duration: '1 Year',
    mode: 'Online',
    eligibility: 'SSLC / Plus Two',
    popular: false,
    icon: '📜',
    badge: 'Short Term',
    feeRange: '₹12,000 – ₹28,000 / year',
    careers: ['Administrative Assistant', 'Computer Operator', 'Junior Manager', 'Field Technician'],
    highlights: ['Quick completion', 'Job-oriented', 'Flexible schedule', 'Govt recognised', 'Certificate + Diploma'],
    universities: ['Aligarh Muslim University', 'Mizoram University', 'GLA University'],
  },
  {
    slug: 'apprenticeship-program',
    title: 'Apprenticeship Program',
    category: 'Apprenticeship',
    description: 'Industry-linked apprenticeship programs that combine learning with real work experience at partner companies.',
    fullDescription: 'The National Apprenticeship Program (NAPS) lets you earn while you learn. Work at a real company, receive a monthly stipend, and earn a government-recognised certificate. TIMS helps you find the right apprenticeship placement and manages all paperwork.',
    duration: '6 Months – 1 Year',
    mode: 'Hybrid',
    eligibility: 'ITI / Diploma holders preferred',
    popular: false,
    icon: '🛠️',
    badge: 'Work & Learn',
    feeRange: 'Government Stipend Provided',
    careers: ['Industry Technician', 'Machine Operator', 'Maintenance Engineer', 'Quality Control'],
    highlights: ['Earn while learning', 'Govt stipend', 'Industry experience', 'NAPS registered', 'Certificate on completion'],
    universities: ['Ministry of Skill Development (NAPS)', 'Partner Industry Companies'],
  },
  {
    slug: 'skill-courses',
    title: 'Skill Courses',
    category: 'Skill Development',
    description: 'Job-ready skill development courses in digital marketing, accounting, programming, spoken English and more.',
    fullDescription: 'Our skill development courses are 3-6 month programs designed to make you job-ready fast. Popular courses include Digital Marketing, Tally & GST Accounting, Python Programming, Spoken English, and Graphic Design. Certificates are industry recognised.',
    duration: '3–6 Months',
    mode: 'Online',
    eligibility: 'Open to all',
    popular: true,
    icon: '💡',
    badge: 'Job Ready',
    feeRange: '₹4,000 – ₹12,000',
    careers: ['Digital Marketer', 'Accountant', 'Programmer', 'Content Creator', 'Freelancer'],
    highlights: ['Fast completion', 'Industry certificates', 'Live projects', 'Job assistance', 'Affordable fees'],
    universities: ['TIMS Certified', 'Google / Meta Partners', 'NSDC Affiliated'],
  },
]

export const UNIVERSITIES = [
  /* ── 10th / Plus Two boards ── */
  {
    slug: 'nios',
    name: 'National Institute of Open Schooling',
    shortName: 'NIOS',
    logo: '/universities/nios.png',
    naac: '-',
    type: 'National Board',
    established: 1989,
    location: 'Noida, Uttar Pradesh',
    description: 'NIOS is India\'s largest open schooling system under the Ministry of Education. It offers Secondary (Class 10) and Senior Secondary (Class 12) programs through open and distance learning, recognised by all Indian universities and employers.',
    programs: ['Secondary (Class 10)', 'Senior Secondary (Class 12)', 'Vocational Courses', 'Open Basic Education'],
    accreditations: ['Ministry of Education', 'Equivalent to CBSE/State Board', 'Accepted by all Indian universities'],
    highlights: ['Largest open school in the world', 'On-demand exams available', 'Study from anywhere', 'Valid for all competitive exams'],
    feeRange: '₹2,000 – ₹6,000 / year',
    website: 'www.nios.ac.in',
    filterTags: ['10th/Plus Two', 'Examination'],
  },
  {
    slug: 'jamia-urdu',
    name: 'Jamia Urdu Aligarh',
    shortName: 'JUAL',
    logo: '/universities/jual.png',
    naac: '-',
    type: 'Urdu Board',
    established: 1938,
    location: 'Aligarh, Uttar Pradesh',
    description: 'Jamia Urdu Aligarh is one of India\'s oldest distance education bodies for Urdu-medium learners. Its Munshi and Fazil programs are equivalent to Class 10 and Class 12, widely recognised across India for government jobs and higher education.',
    programs: ['Munshi (10th equivalent)', 'Moulvi (10th advanced)', 'Fazil (12th equivalent)', 'Kamil (Graduation)'],
    accreditations: ['Equivalent to Class 10 & 12', 'Recognised by Indian universities', 'Valid for Urdu-medium government posts'],
    highlights: ['Urdu-medium instruction', 'Exam centres across Kerala', 'Low fee structure', 'Accepted for Kerala PSC'],
    feeRange: '₹1,500 – ₹4,000 / year',
    website: 'www.jamia-urdu.com',
    filterTags: ['10th/Plus Two', 'Examination'],
  },
  {
    slug: 'bosse',
    name: 'Board of Open Schooling & Skill Education',
    shortName: 'BOSSE',
    logo: '/universities/bosse.png',
    naac: '-',
    type: 'Open Board',
    established: 2014,
    location: 'New Delhi',
    description: 'BOSSE is a UGC-recognised open schooling board offering Secondary and Senior Secondary programs with integrated vocational and skill education components. Ideal for students seeking both academic qualification and practical skill certification.',
    programs: ['Secondary (Class 10)', 'Senior Secondary (Class 12)', 'Skill-integrated curriculum'],
    accreditations: ['UGC Recognised', 'Ministry of Skills Approved', 'Accepted by Indian universities'],
    highlights: ['Skill + academics combined', 'Flexible exam schedule', 'Vocational electives', 'Recognised for higher studies'],
    feeRange: '₹2,500 – ₹7,000 / year',
    website: 'www.bosse.ac.in',
    filterTags: ['10th/Plus Two', 'Examination'],
  },
  /* ── Degree / PG universities ── */
  {
    slug: 'aligarh-muslim-university',
    name: 'Aligarh Muslim University',
    shortName: 'AMU',
    logo: '/universities/amu.png',
    naac: 'A+',
    type: 'Central University',
    established: 1875,
    location: 'Aligarh, Uttar Pradesh',
    description: 'One of India\'s oldest and most prestigious central universities, AMU offers a wide range of UG and PG programs through distance mode. Its distance education programs are UGC-DEB approved and nationally recognised.',
    programs: ['BA', 'BCom', 'BSc', 'MA', 'MCom', 'MSc', 'MBA', 'Diploma in various disciplines'],
    accreditations: ['UGC-DEB Approved', 'NAAC A+', 'NIRF Ranked', 'AIU Member'],
    highlights: ['Established 1875', 'Central University status', 'Pan-India recognition', 'Strong alumni network', 'Research-focused curriculum'],
    feeRange: '₹15,000 – ₹45,000 / year',
    website: 'www.amu.ac.in',
    filterTags: ['Degree/PG', 'Study Materials', 'Examination'],
  },
  {
    slug: 'mizoram-university',
    name: 'Mizoram University',
    shortName: 'MZU',
    logo: '/universities/mzu.png',
    naac: 'A',
    type: 'Central University',
    established: 2001,
    location: 'Aizawl, Mizoram',
    description: 'Mizoram University is a central university established by an Act of Parliament. Its distance education wing offers affordable and recognised programs ideal for students who cannot attend regular classes.',
    programs: ['BA', 'BCom', 'BSc', 'MA', 'MCom', 'Certificate Courses'],
    accreditations: ['UGC-DEB Approved', 'NAAC A', 'Central University'],
    highlights: ['Affordable fee structure', 'UGC approved programs', 'Flexible exam schedule', 'Student-friendly support'],
    feeRange: '₹8,000 – ₹25,000 / year',
    website: 'www.mzu.edu.in',
    filterTags: ['Degree/PG', 'Study Materials', 'Examination'],
  },
  {
    slug: 'guru-kashi-university',
    name: 'Guru Kashi University',
    shortName: 'GKU',
    logo: '/universities/gku.png',
    naac: 'A',
    type: 'State University',
    established: 2011,
    location: 'Talwandi Sabo, Punjab',
    description: 'Guru Kashi University is a UGC-recognised state private university known for its industry-linked programs and student-centric approach. Its online programs are NAAC accredited and widely recognised across India.',
    programs: ['BBA', 'MBA', 'BCA', 'MCA', 'BCom', 'MCom', 'BA', 'MA', 'B.Ed'],
    accreditations: ['UGC-DEB Approved', 'NAAC A', 'AIU Member', 'AICTE Approved'],
    highlights: ['Industry-aligned MBA', 'Strong placement record', 'Affordable fees', 'Weekend batch options'],
    feeRange: '₹20,000 – ₹55,000 / year',
    website: 'www.gurukashiuniversity.in',
    filterTags: ['Degree/PG', 'Study Materials', 'Examination'],
  },
  {
    slug: 'subharti-university',
    name: 'Swami Vivekanand Subharti University',
    shortName: 'SVSU',
    logo: '/universities/svsu.png',
    naac: 'A',
    type: 'Private University',
    established: 2008,
    location: 'Meerut, Uttar Pradesh',
    description: 'Subharti University is one of North India\'s fastest growing private universities. Its distance education programs span management, law, education, science, and arts — all fully approved by UGC-DEB.',
    programs: ['BA', 'BCom', 'BBA', 'BSc', 'MA', 'MCom', 'MBA', 'LLB', 'B.Ed', 'M.Ed'],
    accreditations: ['UGC-DEB Approved', 'NAAC A', 'Bar Council of India', 'NCTE Approved'],
    highlights: ['Widest program range', 'Law programs available', 'Education degrees', 'Lateral entry options'],
    feeRange: '₹18,000 – ₹50,000 / year',
    website: 'www.subharti.org',
    filterTags: ['Degree/PG', 'Study Materials', 'Examination'],
  },
  {
    slug: 'andhra-university',
    name: 'Andhra University',
    shortName: 'AU',
    logo: '/universities/au.png',
    naac: 'A+',
    type: 'State University',
    established: 1926,
    location: 'Visakhapatnam, Andhra Pradesh',
    description: 'Andhra University is one of South India\'s premier state universities, founded in 1926. Its Centre for Distance Education offers a wide range of programs that are fully UGC-DEB approved and NAAC accredited at A+.',
    programs: ['BA', 'BCom', 'BSc', 'BBA', 'MA', 'MCom', 'MBA', 'MSc', 'Diploma Programs'],
    accreditations: ['UGC-DEB Approved', 'NAAC A+', 'AIU Member', 'NIRF Top 100'],
    highlights: ['Est. 1926 — heritage institution', 'South India recognised', 'Affordable fees', 'Strong research culture'],
    feeRange: '₹12,000 – ₹35,000 / year',
    website: 'www.andhrauniversity.edu.in',
    filterTags: ['Degree/PG', 'Study Materials', 'Examination'],
  },
  {
    slug: 'jain-university',
    name: 'Jain University',
    shortName: 'JU',
    logo: '/universities/jain.png',
    naac: 'A++',
    type: 'Deemed University',
    established: 2009,
    location: 'Bangalore, Karnataka',
    description: 'Jain University is a NAAC A++ accredited deemed university and one of the top institutions for online education in India. Its CMS (Centre for Management Studies) online programs are highly respected by employers nationwide.',
    programs: ['BBA', 'BCom', 'BCA', 'MBA', 'MCA', 'MCom', 'BSc Data Science', 'MSc Analytics'],
    accreditations: ['UGC-DEB Approved', 'NAAC A++', 'AICTE Approved', 'ISO 9001:2015'],
    highlights: ['NAAC A++ — highest grade', 'Industry-led curriculum', 'Live mentoring sessions', 'Strong placement cell', 'Data Science specialisation'],
    feeRange: '₹35,000 – ₹80,000 / year',
    website: 'www.jainuniversity.ac.in',
    filterTags: ['Degree/PG', 'Examination'],
  },
  {
    slug: 'gla-university',
    name: 'GLA University',
    shortName: 'GLA',
    logo: '/universities/gla.png',
    naac: 'A+',
    type: 'Deemed University',
    established: 1991,
    location: 'Mathura, Uttar Pradesh',
    description: 'GLA University is a NAAC A+ accredited deemed university known for its engineering and management programs. Its online division offers flexible programs with strong industry connections and placement support.',
    programs: ['BBA', 'MBA', 'BCA', 'MCA', 'BCom', 'MCom', 'B.Tech (CS)', 'M.Tech'],
    accreditations: ['UGC-DEB Approved', 'NAAC A+', 'AICTE Approved', 'NBA Accredited'],
    highlights: ['Engineering + Management combo', 'Tech-focused programs', 'Strong North India placement', 'Industry tie-ups'],
    feeRange: '₹25,000 – ₹70,000 / year',
    website: 'www.gla.ac.in',
    filterTags: ['Degree/PG', 'Study Materials', 'Examination'],
  },
  {
    slug: 'manipal-university',
    name: 'Manipal University',
    shortName: 'MU',
    logo: '/universities/manipal.png',
    naac: 'A++',
    type: 'Deemed University',
    established: 1953,
    location: 'Manipal, Karnataka',
    description: 'Manipal University is one of India\'s most prestigious institutions and a pioneer in online education. Manipal Online offers UGC-DEB approved programs with live classes, recorded sessions, and robust placement support.',
    programs: ['BBA', 'MBA', 'BCA', 'MCA', 'BCom', 'MCom', 'MA', 'MSc Data Science'],
    accreditations: ['UGC-DEB Approved', 'NAAC A++', 'AICTE Approved', 'QS World Ranked'],
    highlights: ['QS World Ranked', 'NAAC A++ prestigious', 'Global alumni network', 'Top employer recognition', 'Advanced LMS platform'],
    feeRange: '₹45,000 – ₹1,20,000 / year',
    website: 'www.manipal.edu',
    filterTags: ['Degree/PG', 'Study Materials', 'Examination'],
  },
  {
    slug: 'amrita-university',
    name: 'Amrita University',
    shortName: 'AU',
    logo: '/universities/amrita.png',
    naac: 'A++',
    type: 'Deemed University',
    established: 2003,
    location: 'Coimbatore, Tamil Nadu',
    description: 'Amrita Vishwa Vidyapeetham is ranked among India\'s top 10 universities and offers exceptional online programs. Its NAAC A++ rating and QS Asia ranking make it one of the most credible institutions for online learning.',
    programs: ['MBA', 'MCA', 'MSc Data Science', 'MSc AI & ML', 'BCom', 'BBA', 'BCA'],
    accreditations: ['UGC-DEB Approved', 'NAAC A++', 'QS Asia Ranked', 'NIRF Top 10'],
    highlights: ['NIRF Top 10 in India', 'AI & Data Science focus', 'Research-driven programs', 'South India heritage', 'Industry collaborations'],
    feeRange: '₹50,000 – ₹1,30,000 / year',
    website: 'www.amrita.edu',
    filterTags: ['Degree/PG', 'Study Materials', 'Examination'],
  },
]

export const TESTIMONIALS = [
  {
    name: 'Sneha K.',
    program: 'MCA – Online',
    quote: 'TIMS provided exceptional support throughout my MCA journey. The infrastructure, instructor communication, and real-world skill application made all the difference in landing my dream job.',
    rating: 5,
    avatar: '/testimonials/sneha.jpg',
  },
  {
    name: 'Reshma A.',
    program: 'MCom – Distance',
    quote: 'As a working professional, TIMS helped me balance work and education perfectly. Their counsellors guided me at every step and the flexible schedule was a game changer.',
    rating: 5,
    avatar: '/testimonials/reshma.jpg',
  },
  {
    name: 'Aiswarya M.',
    program: 'MSc – Online',
    quote: 'I never thought higher education would be this accessible. TIMS opened doors I thought were closed for me. Highly recommend to anyone looking for quality distance education.',
    rating: 5,
    avatar: '/testimonials/aiswarya.jpg',
  },
]

export const STATS = [
  { value: 15, suffix: '+', label: 'Years of Excellence', icon: '🏆' },
  { value: 10000, suffix: '+', label: 'Alumni Worldwide', icon: '👨‍🎓' },
  { value: 98, suffix: '%', label: 'Student Satisfaction', icon: '⭐' },
  { value: 9, suffix: '+', label: 'Partner Universities', icon: '🏛️' },
]

export const FEATURES = [
  { title: 'UGC / NAAC Approved', description: 'All programs offered through UGC-DEB approved and NAAC accredited universities — recognised across India.', icon: '✅', color: 'bg-blue-50 text-blue-700' },
  { title: '100% Online Learning', description: 'Study anytime, anywhere with our fully digital learning management system — no need to leave your city.', icon: '💻', color: 'bg-green-50 text-green-700' },
  { title: 'Affordable Fee Structure', description: 'Quality education should not be a luxury. We offer transparent, affordable fees with scholarship options.', icon: '💰', color: 'bg-yellow-50 text-yellow-700' },
  { title: '24/7 Student Support', description: 'Our dedicated counsellors and support team are always available to guide you through every step.', icon: '🎧', color: 'bg-purple-50 text-purple-700' },
]

export const SERVICES = [
  { title: 'Certificate Attestation', description: 'We help students get their academic certificates attested for overseas use.', icon: '📋' },
  { title: 'Credit Transfer', description: 'Seamless credit transfer facility for students switching universities or programs.', icon: '🔄' },
  { title: 'Embassy Attestation', description: 'Full support for embassy attestation required for foreign employment or study.', icon: '🌐' },
  { title: 'Online Study Assistance', description: 'Dedicated academic support team to help students with online coursework.', icon: '📖' },
]

export const WHY_TIMS = [
  { title: 'Expert Counselling', description: 'Our trained counsellors assess your background, goals, and budget to recommend the best-fit program — completely free of charge.', icon: '🧭', step: '01' },
  { title: 'Simplified Admission', description: 'We handle all the paperwork and university liaison so you can focus on learning. Admission done in days, not weeks.', icon: '📝', step: '02' },
  { title: 'Scholarship Support', description: 'We identify and apply for scholarships on behalf of deserving students, making education even more affordable.', icon: '🎖️', step: '03' },
]

export const BLOG_POSTS = [
  {
    slug: 'ugc-deb-approved-online-degrees',
    title: 'What is UGC-DEB Approval and Why It Matters for Online Degrees?',
    excerpt: 'Understanding UGC-DEB approval is crucial before enrolling in any online degree program. Here is everything you need to know to make an informed decision.',
    content: `UGC-DEB stands for University Grants Commission – Distance Education Bureau. It is the regulatory body in India that approves universities to offer distance and online education programs.\n\nBefore enrolling in any online degree, you must verify that the university has UGC-DEB approval. Without this, your degree may not be recognised by employers or for government job applications.\n\nAt TIMS, all our partner universities are UGC-DEB approved, giving you complete confidence that your degree is legitimate and nationally recognised.`,
    category: 'Education Guide',
    author: 'TIMS Team',
    date: '2024-10-15',
    readTime: '5 min read',
    icon: '📋',
    tags: ['UGC-DEB', 'Online Education', 'Degrees', 'Accreditation'],
    featured: true,
  },
  {
    slug: 'distance-vs-online-education',
    title: 'Distance Education vs Online Education: What is the Difference?',
    excerpt: 'Many students confuse distance and online education. This guide breaks down the key differences to help you choose the right mode of learning.',
    content: `Distance education and online education are often used interchangeably, but they have important differences.\n\nDistance education typically involves study materials sent by post, periodic contact classes, and exams at designated centres. Online education, on the other hand, uses internet platforms for live classes, recorded lectures, and online exams.\n\nBoth modes are recognised by UGC and valid for employment. TIMS offers both options, helping you choose based on your internet access and schedule.`,
    category: 'Education Guide',
    author: 'TIMS Team',
    date: '2024-09-20',
    readTime: '4 min read',
    icon: '🖥️',
    tags: ['Distance Education', 'Online Education', 'Learning Modes'],
    featured: false,
  },
  {
    slug: 'top-online-mba-universities-india',
    title: 'Top 5 Online MBA Universities Approved by UGC in India (2024)',
    excerpt: 'Planning to do an MBA online? Here are the top UGC-approved universities for online MBA programs — with key details on fees, duration and placement support.',
    content: `An MBA can transform your career — and you no longer need to quit your job or relocate to get one. Here are the top 5 UGC-approved universities for online MBA in India.\n\n1. Manipal University Online\n2. Amrita University\n3. Jain University\n4. Andhra University\n5. Guru Kashi University\n\nAll of these are available through TIMS. Our counsellors will help you choose based on your specialisation, budget, and schedule.`,
    category: 'University Spotlight',
    author: 'TIMS Team',
    date: '2024-08-10',
    readTime: '6 min read',
    icon: '🏆',
    tags: ['MBA', 'Universities', 'Management', 'Careers'],
    featured: false,
  },
  {
    slug: 'working-professionals-online-degree',
    title: 'How Working Professionals Can Complete a Degree Without Quitting Their Job',
    excerpt: 'Balancing work and education is challenging — but entirely possible with the right strategy and program choice.',
    content: `Thousands of TIMS students are working professionals who complete their degrees without leaving their jobs. Here is how they do it.\n\n1. Choose a fully online program with weekend or evening batches.\n2. Select a university with flexible exam schedules.\n3. Use recorded lectures for revision when commuting.\n4. Set aside 1-2 hours per day for studies.\n5. Use TIMS counsellors to manage all paperwork so you focus only on learning.`,
    category: 'Student Tips',
    author: 'TIMS Team',
    date: '2024-07-25',
    readTime: '7 min read',
    icon: '💼',
    tags: ['Working Professionals', 'Study Tips', 'Career Growth'],
    featured: false,
  },
  {
    slug: 'naac-grading-explained',
    title: 'NAAC Grading System Explained: What Does A++, A+, A Mean?',
    excerpt: 'The NAAC grade of a university reflects its overall quality. A simple breakdown of what these grades mean and why they matter for your degree.',
    content: `NAAC (National Assessment and Accreditation Council) grades universities on a scale that helps students gauge quality.\n\n- A++ (3.51-4.00): Highest quality, top-tier institutions\n- A+ (3.01-3.50): Excellent quality, widely respected\n- A (2.51-3.00): Very good quality, widely recognised\n- B++ (2.01-2.50): Good quality, generally accepted\n\nAll TIMS partner universities hold A or above ratings, ensuring your degree has strong credibility.`,
    category: 'Education Guide',
    author: 'TIMS Team',
    date: '2024-07-05',
    readTime: '3 min read',
    icon: '⭐',
    tags: ['NAAC', 'University Quality', 'Accreditation'],
    featured: false,
  },
  {
    slug: 'skill-courses-career-boost',
    title: 'Top 6 Skill Courses That Can Double Your Salary in 2024',
    excerpt: 'Short-term skill courses have a massive ROI. From digital marketing to cloud computing — discover which courses employers demand most.',
    content: `Skill courses are the fastest route to a salary hike in 2024. Here are the top 6 that TIMS recommends:\n\n1. Digital Marketing (Google/Meta certified)\n2. Data Analytics with Python\n3. Tally Prime + GST Accounting\n4. Spoken English & Communication\n5. Graphic Design (Canva + Adobe)\n6. Cloud Computing Fundamentals\n\nAll these are available through TIMS Online with certificates recognised by employers. Duration: 3-6 months. Fees starting at just ₹4,000.`,
    category: 'Career Tips',
    author: 'TIMS Team',
    date: '2024-06-12',
    readTime: '5 min read',
    icon: '🚀',
    tags: ['Skill Development', 'Salary', 'Career Tips', 'Courses'],
    featured: false,
  },
  {
    slug: 'kerala-students-distance-education',
    title: 'Why Kerala Students Are Choosing Distance Education in 2024',
    excerpt: 'A growing number of Kerala students are opting for distance and online degrees. We explore the reasons behind this trend and what it means for you.',
    content: `Kerala has one of the highest literacy rates in India, yet thousands of students still cannot pursue traditional college education due to work, family, or financial constraints.\n\nDistance and online education has bridged this gap. In 2024, TIMS has seen a 40% rise in enrolments from Kerala — with students from Malappuram, Kozhikode, Thrissur, and Kasaragod benefiting the most.\n\nKey reasons: flexible schedules, lower costs, no relocation required, and fully recognised degrees.`,
    category: 'Student Tips',
    author: 'TIMS Team',
    date: '2024-05-18',
    readTime: '4 min read',
    icon: '🌴',
    tags: ['Kerala', 'Distance Education', 'Trends', 'Students'],
    featured: false,
  },
  {
    slug: 'mba-vs-mcom-which-is-better',
    title: 'MBA vs MCom: Which Is Better for Your Career in 2024?',
    excerpt: 'Two of the most popular PG programs — but which one is right for you? We compare MBA and MCom on fees, career scope, duration, and recognition.',
    content: `MBA and MCom are both excellent postgraduate choices for commerce and management students — but they serve different goals.\n\nMBA:\n- Broader management focus\n- Higher starting salary potential\n- Specialisations: Finance, HR, Marketing, Operations\n- Ideal for leadership and corporate roles\n\nMCom:\n- Deep commerce and accounting focus\n- Lower fee structure\n- Ideal for teaching, audit, and government roles\n- Required for CA and PhD pathways\n\nTIMS counsellors can help you choose based on your current job, salary goals, and eligibility.`,
    category: 'Education Guide',
    author: 'TIMS Team',
    date: '2024-04-22',
    readTime: '6 min read',
    icon: '🎯',
    tags: ['MBA', 'MCom', 'Career Comparison', 'PG Programs'],
    featured: false,
  },
]
